version: '2'

volumes:
  bundle:

services:
  web:
    image: ruby:2.5.7-alpine
    build:
      context: .
    env_file: .env
    environment:
      BUNDLE_PATH: /bundle
    volumes:
      - '.:/usr/src/app'
      - 'bundle:/bundle'
    working_dir: /usr/src/app
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'
    links:
      - postgres

  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
    ports:
      - '15432:5432'
